kumuluzee:
  name: priljubljeni-izdelki-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8082
  datasources:
  - jndi-name: jdbc/IzdelkiDS
    connection-url: jdbc:postgresql://localhost:5432/izdelki
    #connection-url: jdbc:postgresql://34.118.85.117:5432/rso
    #connection-url: jdbc:postgresql://host.docker.internal:5432/izdelki
    username: rso
    password: rso
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="4b832107-c8b2-462c-920a-bc2e83de6d06-ls.logit.io"
                                  port="28664" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/IzdelkiDS
        type: liveness
      disk-space-health-check:
        threshold: 100000000
  metrics:
    web-instrumentation:
      - name: priljubljeni-izdelki-endpoint
        url-pattern: /v1/priljubljeni-izdelki/*
rest-properties:
  simulation: false
